import {chromium, expect} from '@playwright/test';
import {mkdtemp, rm, mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import express from 'express';
import {createApp} from '../server/app.js';

const dir = await mkdtemp(tmpdir() + '/jeffreyys-features-');
const evidence = tmpdir() + '/jeffreyys-evidence';
await mkdir(evidence, {recursive:true});
const app = await createApp({dataFile:dir + '/state.json',demo:true});
app.use(express.static(resolve('dist')));
const server = app.listen(0,'127.0.0.1');
await new Promise(r => server.once('listening',r));
const base = 'http://127.0.0.1:' + server.address().port;
const browser = await chromium.launch({headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Europe/Berlin'});
// Verify our map integration deterministically without depending on a third-party tile server.
await context.route('https://tile.openstreetmap.org/**', route => route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6GOcAAAAASUVORK5CYII=','base64')}));
const page = await context.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
async function login(name,pin) {
  await page.goto(base);
  await page.getByRole('button',{name:new RegExp(name)}).click();
  await page.getByLabel('PIN',{exact:true}).fill(pin);
  await page.getByRole('button',{name:'Anmelden'}).click();
  await page.locator('.sidebar').waitFor();
}
async function nav(name) {await page.locator('.sidebar').getByRole('button',{name,exact:true}).click();}
try {
  await login('Alex','1234');
  await nav('Team');
  await page.getByLabel('Teamrolle').selectOption('kitchen');
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await expect(page.locator('tbody')).toContainText('Samira');
  await page.getByRole('button',{name:'Bearbeiten',exact:true}).click();
  await page.getByLabel('Telefon',{exact:true}).fill('+49 123 456789');
  await page.getByRole('button',{name:'Speichern',exact:true}).click();
  await expect(page.locator('tbody')).toContainText('+49 123 456789');
  await nav('Zeiten');
  await expect(page.getByRole('columnheader',{name:'Verdienst',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Mitarbeiter · Monat'}).click();
  await expect(page.locator('tbody')).toContainText('Samira');
  await expect(page.getByLabel('Abrechnungsmonat')).toBeVisible();
  await nav('Analyse');
  for (const period of ['90 Tage','365 Tage']) {
    await page.getByRole('button',{name:period,exact:true}).click();
    await expect(page.getByRole('button',{name:period,exact:true})).toHaveClass('selected');
    await page.getByRole('button',{name:'Vorheriger Zeitraum'}).click();
    await page.getByRole('button',{name:'Nächster Zeitraum'}).click();
  }
  await page.getByText('Artikel einer Bestellung erfassen oder korrigieren').click();
  await page.getByLabel('Bestellung',{exact:true}).selectOption('demo-order-1');
  await page.getByRole('button',{name:'+ Artikel',exact:true}).click();
  await page.getByLabel('Artikel 1',{exact:true}).fill('Cheeseburger');
  await page.getByLabel('Menge 1',{exact:true}).fill('2');
  await page.getByLabel('Stückpreis 1',{exact:true}).fill('9.5');
  await page.getByRole('button',{name:'Artikel speichern'}).click();
  const articleTable = page.locator('.panel').filter({has:page.getByRole('heading',{name:'Verkaufte Artikel',exact:true})}).locator('tbody');
  await expect(articleTable).toContainText('Cheeseburger');
  await expect(articleTable).toContainText('19,00');
  await page.screenshot({path:evidence + '/features-analytics.png',fullPage:true});
  await nav('Plan');
  await page.locator('.week-day').first().getByRole('button',{name:'+ Schicht',exact:true}).click();
  await page.getByLabel('Mitarbeiter',{exact:true}).selectOption('samira');
  await page.getByLabel('Beginn',{exact:true}).fill('22:00');
  await page.getByLabel('Ende',{exact:true}).fill('02:00');
  await page.getByRole('button',{name:'Speichern',exact:true}).click();
  await page.getByLabel('Planrolle').selectOption('kitchen');
  const shift = page.locator('.week-day').first().locator('.schedule-shift');
  await expect(shift).toContainText('(+1 Tag)');
  await shift.getByRole('button',{name:'Bearbeiten',exact:true}).click();
  await page.getByLabel('Beginn',{exact:true}).fill('21:00');
  await page.getByRole('button',{name:'Speichern',exact:true}).click();
  await expect(shift).toContainText('21:00');
  await page.screenshot({path:evidence + '/features-plan.png',fullPage:true});
  await shift.getByRole('button',{name:'Bearbeiten',exact:true}).click();
  await page.getByRole('button',{name:'Schicht entfernen'}).click();
  await expect(shift).toHaveCount(0);
  const driver = await browser.newContext();
  await driver.request.post(base + '/api/login',{data:{id:'leo',pin:'3456'}});
  await driver.request.post(base + '/api/action',{data:{type:'saveLocation',latitude:48.14,longitude:11.58}});
  await driver.close();
  await page.getByRole('button',{name:'Abmelden'}).click();
  await login('Samira','2345');
  await expect(page.getByRole('region',{name:'Live-Fahrerkarte'})).toBeVisible();
  await expect(page.locator('.driver-marker[data-driver-id="leo"]')).toHaveAttribute('data-latitude','48.14');
  await expect(page.getByText(/Ø .*Min. je Bestellung/)).toBeVisible();
  await nav('Mein Verdienst');
  await expect(page.locator('.personal-earnings')).toContainText('Samira');
  await expect(page.locator('.personal-earnings')).not.toContainText('Alex');
  await expect(page.locator('.personal-earnings')).not.toContainText('Leo');
  await page.getByLabel('Abrechnungsmonat').fill('2020-01');
  await expect(page.locator('.personal-earnings')).toContainText('0,00');
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(() => document.querySelector('.sidebar').getBoundingClientRect().right <= 1);
  await page.getByRole('button',{name:'Menü',exact:true}).click();
  await nav('Plan');
  await expect(page.getByRole('heading',{name:'Wochenübersicht'})).toBeVisible();
  await page.getByRole('button',{name:'Menü',exact:true}).click();
  await nav('Mein Verdienst');
  await page.waitForFunction(() => document.querySelector('.sidebar').getBoundingClientRect().right <= 1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({path:evidence + '/features-kitchen-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Abmelden'}).click();
  await login('Leo','3456');
  await nav('Belege');
  await page.getByRole('button',{name:'Beleg erfassen',exact:true}).click();
  await page.getByLabel('Bestellnummer',{exact:true}).fill('ITEM-UI');
  await page.getByLabel('Betrag (€)',{exact:true}).fill('10');
  await page.getByLabel('Zahlungsart',{exact:true}).selectOption('online');
  await page.getByLabel('Adressart',{exact:true}).selectOption('true');
  await page.getByRole('button',{name:'+ Artikel',exact:true}).click();
  await page.getByLabel('Artikel 1',{exact:true}).fill('Fries');
  await page.getByLabel('Menge 1',{exact:true}).fill('2');
  await page.getByLabel('Stückpreis 1',{exact:true}).fill('5');
  await page.getByRole('button',{name:'Beleg übernehmen'}).click();
  await expect(page.locator('tbody')).toContainText('ITEM-UI');
  const saved = await (await context.request.get(base + '/api/state')).json();
  expect(saved.orders.find(o => o.orderNumber === 'ITEM-UI').items).toEqual([{name:'Fries',quantity:2,unitPrice:5}]);
  if (errors.length) throw Error(errors.join('\n'));
  console.log('PASS team contact, monthly wages, 90/365-day analysis, articles, schedule edits and kitchen map/own wages; desktop and mobile');
} catch (error) {
  console.error('Browser errors:', errors);
  await page.screenshot({path:evidence + '/features-failure.png',fullPage:true});
  throw error;
} finally {
  await browser.close();
  server.closeAllConnections();
  await new Promise(r => server.close(r));
  await app.locals.close();
  await rm(dir,{recursive:true,force:true});
}
